### ISSUE TITLE
convert_model.py doesn't work

### ISSUE THREAD

**Issue by martenq1337** [Dobiasd/frugally-deep#140]
Hello, I want to use the software for predict images for Unet. Unfortunately, when I try to use convert_model.py script, i've got an error. Is there any way to skip this part, and instead of converting to json, just write into the c++ code?
Spec: Win10 / RTX 2070
A tried with a similar model: https://github.com/zhixuhao/unet
I read after the issue, but I couldn't figure it out. I upgraded keras and tensorflow for the latest version, also restarted the pc to clean gpu memory. I have the latest cuda toolkit, also tried to installed the patches, but none of them worked.
![processes](https://user-images.githubusercontent.com/29870656/58008408-9c9e4780-7aec-11e9-97ca-a1b7ed1eb347.png)

**python convert_model.py unet_spots.h5 c:/**
Using TensorFlow backend.
loading unet_spots.h5
WARNING:tensorflow:From C:\Conda\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-05-20 10:37:01.290784: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-05-20 10:37:01.473652: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.83
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.59GiB
2019-05-20 10:37:01.479302: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-05-20 10:37:01.954201: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-20 10:37:01.957298: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-05-20 10:37:01.959151: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2019-05-20 10:37:01.961226: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6314 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:01:00.0, compute capability: 7.5)
WARNING:tensorflow:From C:\Conda\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Forward pass took 1.742066 s.
Forward pass took 0.009974 s.
Forward pass took 0.009973 s.
Starting performance measurements.
Forward pass took 0.010997 s.
Forward pass took 0.009974 s.
Forward pass took 0.009973 s.
Forward pass took 0.009999 s.
Forward pass took 0.00995 s.
Forward pass took 0.0101786 s on average.
Converting model architecture.
Determining Keras behaviour.
2019-05-20 10:37:05.844886: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library cublas64_90.dll locally
2019-05-20 10:37:06.093145: E tensorflow/stream_executor/cuda/cuda_blas.cc:698] failed to run cuBLAS routine cublasSgemm_v2: CUBLAS_STATUS_EXECUTION_FAILED
Traceback (most recent call last):
  File "C:\Conda\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Conda\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Conda\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=2, n=1, k=1
         [[{{node separable_conv2d}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "convert_model.py", line 837, in <module>
    main()
  File "convert_model.py", line 833, in main
    convert(in_path, out_path, no_tests)
  File "convert_model.py", line 806, in convert
    json_output = model_to_fdeep_json(model, no_tests)
  File "convert_model.py", line 770, in model_to_fdeep_json
    check_operation_offset(depth, offset_sep_conv2d_eval, 'valid')
  File "convert_model.py", line 720, in check_operation_offset
    result = K.eval(output).flatten().tolist()
  File "C:\Conda\lib\site-packages\keras\backend\tensorflow_backend.py", line 673, in eval
    return to_dense(x).eval(session=get_session())
  File "C:\Conda\lib\site-packages\tensorflow\python\framework\ops.py", line 695, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "C:\Conda\lib\site-packages\tensorflow\python\framework\ops.py", line 5181, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "C:\Conda\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Conda\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Conda\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Conda\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=2, n=1, k=1
         [[node separable_conv2d (defined at C:\Conda\lib\site-packages\keras\backend\tensorflow_backend.py:3811) ]]

Caused by op 'separable_conv2d', defined at:
  File "convert_model.py", line 837, in <module>
    main()
  File "convert_model.py", line 833, in main
    convert(in_path, out_path, no_tests)
  File "convert_model.py", line 806, in convert
    json_output = model_to_fdeep_json(model, no_tests)
  File "convert_model.py", line 770, in model_to_fdeep_json
    check_operation_offset(depth, offset_sep_conv2d_eval, 'valid')
  File "convert_model.py", line 719, in check_operation_offset
    output = eval_f(depth, padding, input_data)
  File "convert_model.py", line 698, in offset_sep_conv2d_eval
    pointwise_kernel, strides=(3, 3), padding=padding)
  File "C:\Conda\lib\site-packages\keras\backend\tensorflow_backend.py", line 3811, in separable_conv2d
    data_format=tf_data_format)
  File "C:\Conda\lib\site-packages\tensorflow\python\ops\nn_impl.py", line 681, in separable_conv2d
    name=name)
  File "C:\Conda\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1026, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "C:\Conda\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Conda\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Conda\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Conda\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InternalError (see above for traceback): Blas SGEMM launch failed : m=2, n=1, k=1
         [[node separable_conv2d (defined at C:\Conda\lib\site-packages\keras\backend\tensorflow_backend.py:3811) ]]

[unet_spots.zip](https://github.com/Dobiasd/frugally-deep/files/3196969/unet_spots.zip)

**Comment by Dobiasd** [comment]
There is no way to skip the to-JSON-conversion step.

But your error looks like it is happening outside of frugally-deep code and has something to do with cublas, which is good in that case. :slightly_smiling_face:

So please try to convert your model without GPU, i.e., instead of

```bash
python3 keras_export/convert_model.py keras_model.h5 fdeep_model.json
```

```bash
CUDA_VISIBLE_DEVICES='' python3 keras_export/convert_model.py keras_model.h5 fdeep_model.json
```

**Comment by martenq1337** [comment]
Oh, nearly after 2 days, I've got a solution. I read that a lot of people with RTX card has this issue. I reinstalled tensorflow but doesn't have any impact. So I just I installed tensorflow-eigen, and now it works perfect as normal! Thanks your help.
